version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '3000:3000'
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - '8080:80'
